id: medcom.fhir.dk.conditionlist
canonical: http://medcomfhir.dk/ig/conditionlist
name: MedCom Condition List
title: DK MedCom Condition List
description: The MedCom ConditionList Implementation Guide includes profiles developed exchange a patients diagnoses in a FHIR-document
status: active # draft | active | retired | unknown
version: 1.0.1
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: MedCom
  url: http://www.medcom.dk

dependencies:
  medcom.fhir.dk.terminology: 1.8.1
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.document: 1.0.1
  medcom.fhir.dk.xdsmetadata: 1.0.1
  hl7.fhir.dk.core: 3.2.0

parameters:
  show-inherited-invariants: false
  special-url: [urn:oid:1.2.208.176.2.1, urn:iso:std:iso:11073:10101, urn:oid:1.2.208.176.2.4, urn:oid:1.2.208.176.2.21, urn:oid:1.2.208.176.2.4.12]

menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Examples: examples.html
  Artifacts: artifacts.html
  Downloads: downloads.html

instanceOptions:
  manualSliceOrdering: true # true | false
